// Generated by CIRCT firtool-1.62.0
module top(	// @[src/main/top.scala:5:7]
  input         clock,	// @[src/main/top.scala:5:7]
                reset,	// @[src/main/top.scala:5:7]
  input  [31:0] io_a,	// @[src/main/top.scala:6:16]
                io_b,	// @[src/main/top.scala:6:16]
  output [31:0] io_c	// @[src/main/top.scala:6:16]
);

  assign io_c = io_a * io_b;	// @[src/main/top.scala:5:7, :11:18]
endmodule

